export type BiomoleculeQuestion = {
  id: string;
  code: string;
  eyebrow: string;
  objective: string;
  marks: number;
  skill: "Knowledge" | "Application" | "Image" | "Exam technique";
  difficulty: 1 | 2 | 3;
  prompt: string;
  format?: "mcq" | "image" | "sequence" | "data" | "structured" | "practical";
  options?: string[];
  answer?: number;
  data?: { headers: string[]; rows: string[][] };
  markPoints?: string[];
  modelAnswer?: string;
  hint: string;
  misconception: string;
  explanation: string;
  source: string;
  sourceImage: string;
  sourcePage: number;
};

export const biomoleculeQuestions: BiomoleculeQuestion[] = [
  {
    id: "bio-biomol-alpha-beta",
    code: "1(g)",
    eyebrow: "Verified source · image discrimination",
    objective: "1(g) Biomolecule monomers",
    marks: 1,
    skill: "Knowledge",
    difficulty: 1,
    prompt: "In the ring form shown, the hydroxyl group on carbon 1 is above the plane of the ring. Which monomer is it?",
    options: ["α-glucose", "β-glucose", "Glycerol", "Amino acid"],
    answer: 1,
    hint: "Compare the position of the C1 hydroxyl group with the CH₂OH group.",
    misconception: "α- and β-glucose orientation",
    explanation: "It is β-glucose. In the convention used here, the hydroxyl group on carbon 1 lies above the ring; in α-glucose it lies below.",
    source: "TMJC Biomolecules.pdf · printed p.16 · Fig. 2.2",
    sourceImage: "/materials/biomolecules/page-18.jpg",
    sourcePage: 16,
  },
  {
    id: "bio-biomol-amino-general",
    code: "1(g)",
    eyebrow: "Verified source · retrieval",
    objective: "1(g) Biomolecule monomers",
    marks: 1,
    skill: "Knowledge",
    difficulty: 1,
    prompt: "Which set of groups is bonded to the central carbon in every amino acid?",
    options: ["Amino, carboxyl, hydrogen and R group", "Phosphate, pentose and base", "Three fatty acids and glycerol", "Two hydroxyl groups and a carbonyl"],
    answer: 0,
    hint: "The variable part is the side chain, usually written as R.",
    misconception: "General amino-acid structure",
    explanation: "Every amino acid has an amino group, carboxyl group, hydrogen atom and variable R group attached to its central carbon.",
    source: "TMJC Biomolecules.pdf · amino-acid structure section",
    sourceImage: "/materials/biomolecules/page-65.jpg",
    sourcePage: 58,
  },
  {
    id: "bio-biomol-fatty-acid",
    code: "1(g)",
    eyebrow: "Verified source · transfer",
    objective: "1(g) Biomolecule monomers",
    marks: 2,
    skill: "Application",
    difficulty: 2,
    prompt: "A fatty acid contains one carbon–carbon double bond. Which description is correct?",
    options: ["It is saturated and usually packs tightly", "It is unsaturated and the double bond can introduce a kink", "It is a carbohydrate because it contains carbon", "It must be hydrophilic along its entire length"],
    answer: 1,
    hint: "Saturation refers to whether the hydrocarbon chain holds the maximum possible number of hydrogen atoms.",
    misconception: "Saturated versus unsaturated fatty acids",
    explanation: "A carbon–carbon double bond makes the fatty acid unsaturated and commonly creates a kink, reducing close packing between lipid molecules.",
    source: "TMJC Biomolecules.pdf · printed p.36 · Fig. 3.4",
    sourceImage: "/materials/biomolecules/page-38.jpg",
    sourcePage: 36,
  },
  {
    id: "bio-biomol-glycosidic",
    code: "1(h)",
    eyebrow: "Verified source · bond formation",
    objective: "1(h) Formation and breakage of bonds",
    marks: 2,
    skill: "Knowledge",
    difficulty: 1,
    prompt: "What happens when two monosaccharides form a glycosidic bond?",
    options: ["Water is added in an oxidation reaction", "Water is removed in a condensation reaction", "Carbon dioxide is removed in hydrolysis", "ATP is always consumed"],
    answer: 1,
    hint: "One monomer contributes H and the other contributes OH.",
    misconception: "Condensation versus hydrolysis",
    explanation: "A condensation reaction removes one molecule of water while a covalent glycosidic bond forms between the monosaccharides.",
    source: "TMJC Biomolecules.pdf · printed p.18 · glycosidic bonds",
    sourceImage: "/materials/biomolecules/page-20.jpg",
    sourcePage: 18,
  },
  {
    id: "bio-biomol-hydrolysis",
    code: "1(h)",
    eyebrow: "Verified source · reverse reasoning",
    objective: "1(h) Formation and breakage of bonds",
    marks: 2,
    skill: "Application",
    difficulty: 2,
    prompt: "During digestion, a disaccharide is split into two monosaccharides. Which statement best describes the reaction?",
    options: ["A water molecule is used to hydrolyse the glycosidic bond", "A water molecule is released to form an ester bond", "Hydrogen bonds become peptide bonds", "The monosaccharides are oxidised into amino acids"],
    answer: 0,
    hint: "Hydrolysis literally uses water to split a bond.",
    misconception: "Direction of bond reactions",
    explanation: "Hydrolysis adds the components of water across the glycosidic bond, breaking it and restoring hydroxyl groups on the products.",
    source: "TMJC Biomolecules.pdf · printed p.18 · Fig. 2.4",
    sourceImage: "/materials/biomolecules/page-20.jpg",
    sourcePage: 18,
  },
  {
    id: "bio-biomol-ester-count",
    code: "1(h)",
    eyebrow: "Verified source · molecular accounting",
    objective: "1(h) Formation and breakage of bonds",
    marks: 2,
    skill: "Application",
    difficulty: 2,
    prompt: "How many ester bonds and water molecules are produced when one triglyceride forms from glycerol and three fatty acids?",
    options: ["1 ester bond and 1 water", "2 ester bonds and 2 water", "3 ester bonds and 3 water", "4 ester bonds and no water"],
    answer: 2,
    hint: "Each fatty acid attaches to one of glycerol’s three hydroxyl groups.",
    misconception: "Triglyceride condensation stoichiometry",
    explanation: "Three condensation reactions occur, forming three ester bonds and releasing three water molecules.",
    source: "TMJC Biomolecules.pdf · printed p.34 · triglyceride formation",
    sourceImage: "/materials/biomolecules/page-36.jpg",
    sourcePage: 34,
  },
  {
    id: "bio-biomol-starch-branches",
    code: "1(i)",
    eyebrow: "Verified source · image reasoning",
    objective: "1(i) Biomolecule structure and function",
    marks: 2,
    skill: "Knowledge",
    difficulty: 2,
    prompt: "Which structural feature distinguishes amylopectin from amylose?",
    options: ["β-1,4 bonds only", "α-1,6 bonds create branch points", "Peptide bonds form a helix", "Fatty acids form cross-links"],
    answer: 1,
    hint: "Look for the bond found at each branch point.",
    misconception: "Amylose versus amylopectin",
    explanation: "Both contain α-1,4 glycosidic bonds, but amylopectin also contains α-1,6 glycosidic bonds at branch points.",
    source: "TMJC Biomolecules.pdf · printed p.21 · Fig. 2.8",
    sourceImage: "/materials/biomolecules/page-23.jpg",
    sourcePage: 21,
  },
  {
    id: "bio-biomol-glycogen",
    code: "1(i)",
    eyebrow: "Verified source · structure to function",
    objective: "1(i) Biomolecule structure and function",
    marks: 3,
    skill: "Exam technique",
    difficulty: 2,
    prompt: "Why can glycogen provide glucose rapidly when energy demand rises?",
    options: ["It is insoluble and has no chain ends", "It is highly branched, giving many ends for enzyme action", "It contains β-glucose and forms fibres", "It crosses membranes without transport proteins"],
    answer: 1,
    hint: "Link branching to the number of sites at which enzymes can work simultaneously.",
    misconception: "Glycogen structure–function link",
    explanation: "Its many α-1,6 branch points create numerous terminal glucose residues, so several enzymes can release glucose at the same time.",
    source: "TMJC Biomolecules.pdf · printed p.22 · glycogen",
    sourceImage: "/materials/biomolecules/page-24.jpg",
    sourcePage: 22,
  },
  {
    id: "bio-biomol-cellulose",
    code: "1(i)",
    eyebrow: "Verified source · unfamiliar context",
    objective: "1(i) Biomolecule structure and function",
    marks: 3,
    skill: "Application",
    difficulty: 3,
    prompt: "A mutation prevents hydrogen bonds forming between adjacent cellulose chains. What is the most direct consequence for a plant cell wall?",
    options: ["Greater tensile strength", "Lower tensile strength because fewer microfibrils are stabilised", "Faster glucose release for respiration", "More α-1,6 branch points"],
    answer: 1,
    hint: "The glycosidic bonds build each chain; hydrogen bonds hold neighbouring chains together.",
    misconception: "Cellulose hierarchy and tensile strength",
    explanation: "Parallel β-glucose chains are cross-linked by many hydrogen bonds into microfibrils. Losing those interactions reduces tensile strength.",
    source: "TMJC Biomolecules.pdf · printed p.24 · cellulose",
    sourceImage: "/materials/biomolecules/page-26.jpg",
    sourcePage: 24,
  },
  {
    id: "bio-biomol-phospholipid",
    code: "1(i)",
    eyebrow: "Verified source · image reasoning",
    objective: "1(i) Biomolecule structure and function",
    marks: 2,
    skill: "Application",
    difficulty: 2,
    prompt: "Why do phospholipids spontaneously form a bilayer in water?",
    options: ["Both ends are hydrophobic", "Hydrophilic heads face water while hydrophobic tails turn away", "Their heads form peptide bonds", "Their tails are charged and attract water"],
    answer: 1,
    hint: "A phospholipid is amphipathic: its two regions interact differently with water.",
    misconception: "Phospholipid amphipathic behaviour",
    explanation: "Polar phosphate-containing heads interact with water, while non-polar fatty-acid tails avoid it, producing a stable bilayer arrangement.",
    source: "TMJC Biomolecules.pdf · printed p.38 · phospholipids",
    sourceImage: "/materials/biomolecules/page-40.jpg",
    sourcePage: 38,
  },
  {
    id: "bio-biomol-energy-store",
    code: "1(i)",
    eyebrow: "Verified source · comparative application",
    objective: "1(i) Biomolecule structure and function",
    marks: 2,
    skill: "Application",
    difficulty: 3,
    prompt: "Why are triglycerides efficient long-term energy stores compared with carbohydrates of the same mass?",
    options: ["They contain proportionally more C–H bonds and release more energy on oxidation", "They dissolve freely in cytoplasm", "They are polymers of glucose", "They contain nitrogen-rich peptide bonds"],
    answer: 0,
    hint: "Compare the degree of reduction of their carbon atoms.",
    misconception: "Lipid energy-storage advantage",
    explanation: "Triglycerides have many energy-rich C–H bonds and are more reduced, so complete oxidation releases more energy per unit mass.",
    source: "TMJC Biomolecules.pdf · printed p.37 · lipid functions",
    sourceImage: "/materials/biomolecules/page-38.jpg",
    sourcePage: 37,
  },
  {
    id: "bio-biomol-osmosis-store",
    code: "1(i)",
    eyebrow: "Verified source · biological consequence",
    objective: "1(i) Biomolecule structure and function",
    marks: 2,
    skill: "Application",
    difficulty: 3,
    prompt: "Why is storing glucose as insoluble starch safer for a plant cell than storing the same number of free glucose molecules?",
    options: ["Starch increases water potential sharply", "Starch has little osmotic effect, reducing water entry", "Starch diffuses out through the membrane", "Starch is chemically identical to cellulose"],
    answer: 1,
    hint: "Osmotic effect depends strongly on the number of dissolved particles.",
    misconception: "Storage polysaccharides and osmosis",
    explanation: "Packaging many glucose units into insoluble starch greatly reduces the number of dissolved particles and therefore its effect on cell water potential.",
    source: "TMJC Biomolecules.pdf · printed p.21 · starch structure and function",
    sourceImage: "/materials/biomolecules/page-23.jpg",
    sourcePage: 21,
  },
];

export const biomoleculeAnswerKey = Object.fromEntries(
  biomoleculeQuestions.map((question) => [question.id, question]),
);
