import type { BiomoleculeQuestion } from "./biomolecules.ts";

type PackKey = "cycle" | "gene" | "mutation" | "technique";
type Seed = {
  id: string; code: string; page: number; prompt: string;
  options?: string[]; answer?: number; explanation?: string;
  format?: BiomoleculeQuestion["format"]; data?: BiomoleculeQuestion["data"];
  markPoints?: string[]; hint?: string; difficulty?: 1 | 2 | 3;
};

const packMeta = {
  cycle: { file: "The Cell Cycle.pdf", dir: "cell-cycle" },
  gene: { file: "DNA Replication & Gene Expression.pdf", dir: "gene-expression" },
  mutation: { file: "DNA Mutations & Its Consequences.pdf", dir: "mutations" },
  technique: { file: "Molecular Techniques in DNA Analysis.pdf", dir: "techniques" },
} as const;

const objectives: Record<string, string> = {
  "2(a)": "DNA replication and the end-replication problem",
  "2(b)": "Gene expression in prokaryotes and eukaryotes",
  "2(k)": "Molecular techniques in DNA analysis",
  "2(l)": "Gene mutations and chromosome aberrations",
  "2(m)": "Mutation and genetic disease",
  "2(n)": "Mitotic cell cycle",
  "2(o)": "Significance and regulation of mitosis",
  "2(p)": "Factors increasing cancer risk",
  "2(q)": "Oncogenes and tumour-suppressor genes",
  "2(r)": "Multi-step development of cancer",
  "2(s)": "Meiotic cell cycle",
  "2(t)": "Meiosis, fertilisation and variation",
};

function build(pack: PackKey, seeds: Seed[]): BiomoleculeQuestion[] {
  const meta = packMeta[pack];
  return seeds.map((seed) => {
    const written = Boolean(seed.markPoints?.length);
    const format = seed.format ?? "mcq";
    const skill = format === "image" ? "Image" : written || format === "practical" ? "Exam technique" : format === "mcq" ? "Knowledge" : "Application";
    return {
      id: `bio-${pack}-${seed.id}`,
      code: seed.code,
      eyebrow: `${format === "mcq" ? "Verified source" : format.replace(/^./, (letter) => letter.toUpperCase())} · Core 2`,
      objective: `${seed.code} ${objectives[seed.code]}`,
      marks: written ? seed.markPoints!.length : seed.difficulty === 3 ? 3 : 2,
      skill,
      difficulty: seed.difficulty ?? 2,
      prompt: seed.prompt,
      format,
      options: seed.options,
      answer: seed.answer,
      data: seed.data,
      markPoints: seed.markPoints,
      modelAnswer: written ? seed.markPoints!.join(" ") : undefined,
      hint: seed.hint ?? "Use the biological mechanism and the evidence in the question, not a memorised keyword alone.",
      misconception: objectives[seed.code],
      explanation: seed.explanation ?? (written ? "Award one mark for each distinct, correctly linked point." : seed.options?.[seed.answer ?? 0] ?? "Review the source mechanism."),
      source: `${meta.file} · PDF p.${seed.page}`,
      sourceImage: `/materials/${meta.dir}/page-${seed.page}.jpg`,
      sourcePage: seed.page,
    };
  });
}

export const cellCycleQuestions = build("cycle", [
  { id:"g1",code:"2(n)",page:24,prompt:"Which event is characteristic of G1 rather than S phase?",options:["DNA replication","Cell growth and organelle synthesis","Separation of sister chromatids","Pairing of homologous chromosomes"],answer:1,explanation:"G1 is a growth phase; nuclear DNA is replicated during S phase." },
  { id:"s-phase",code:"2(n)",page:24,prompt:"A diploid cell enters S phase. What changes by the end of S phase?",options:["Chromosome number doubles","DNA mass doubles while chromosome number is unchanged","Ploidy halves","Homologous chromosomes separate"],answer:1,explanation:"Each chromosome becomes two sister chromatids, doubling DNA mass without changing chromosome number." },
  { id:"g2",code:"2(n)",page:24,prompt:"What is the main role of G2 before nuclear division?",options:["DNA is replicated for the first time","The cell prepares proteins and organelles required for division","Homologues cross over","The nuclear envelope reforms"],answer:1 },
  { id:"prophase",code:"2(n)",page:32,prompt:"Which change occurs during mitotic prophase?",options:["Chromatin condenses and the spindle begins to form","Centromeres divide and chromatids move apart","Chromosomes decondense","Homologues form bivalents"],answer:0 },
  { id:"metaphase",code:"2(n)",page:32,prompt:"Why are chromosomes aligned at the metaphase plate?",options:["To allow DNA replication","So sister chromatids can be attached to opposite spindle poles before equal separation","To permit crossing over","To reform nucleoli"],answer:1 },
  { id:"anaphase",code:"2(n)",page:32,prompt:"What initiates mitotic anaphase?",options:["Replication of centromeres","Division of centromeres followed by separation of sister chromatids","Synapsis of homologues","Breakdown of spindle fibres"],answer:1 },
  { id:"telophase",code:"2(n)",page:32,prompt:"Which event occurs during telophase?",options:["DNA replication","Homologues pair","Nuclear envelopes reform around separated chromosome sets","Chromosomes align at the equator"],answer:2 },
  { id:"cytokinesis",code:"2(n)",page:32,prompt:"How does cytokinesis differ in plant and animal cells?",options:["Only plant cells divide","Animal cells form a cleavage furrow; plant cells form a cell plate","Plant cells use centrioles only","Animal cells build a new cell wall"],answer:1 },
  { id:"mitosis-significance",code:"2(o)",page:38,prompt:"Why does mitosis support growth and tissue repair?",options:["It generates haploid cells","It produces genetically similar daughter cells with the same chromosome number","It always creates new alleles","It halves DNA content permanently"],answer:1 },
  { id:"g1-checkpoint",code:"2(o)",page:38,prompt:"Which condition is assessed at the G1 checkpoint?",options:["Whether homologues have crossed over","Cell size, nutrients, growth signals and DNA damage","Whether chromatids reached opposite poles","Whether fertilisation occurred"],answer:1 },
  { id:"g2-checkpoint",code:"2(o)",page:38,prompt:"Why can the G2 checkpoint prevent transmission of mutations?",options:["It stops a cell with damaged or incompletely replicated DNA entering mitosis","It removes every mutation from the genome","It prevents S phase","It separates homologues"],answer:0 },
  { id:"m-checkpoint",code:"2(o)",page:38,prompt:"What must be true before the spindle checkpoint permits anaphase?",options:["Every chromosome has replicated again","Kinetochores are correctly attached to spindle fibres from opposite poles","The nuclear envelope is intact","Crossing over is complete"],answer:1 },
  { id:"cancer",code:"2(o)",page:38,prompt:"How can checkpoint dysregulation contribute to cancer?",options:["Damaged cells continue dividing instead of arresting or dying","All cells enter G0","DNA replication stops permanently","Meiosis replaces mitosis"],answer:0 },
  { id:"meiosis-one",code:"2(s)",page:43,prompt:"What separates during anaphase I of meiosis?",options:["Sister chromatids","Homologous chromosomes","DNA nucleotides","Centrioles from chromosomes"],answer:1 },
  { id:"meiosis-two",code:"2(s)",page:45,prompt:"What separates during anaphase II?",options:["Homologous chromosome pairs","Sister chromatids after centromeres divide","Bivalents without centromere division","Alleles from DNA"],answer:1 },
  { id:"cycle-image",code:"2(n)",page:24,format:"image",prompt:"The source figure shows a cell with uncondensed chromatin and replicated DNA. Which stage follows S phase before mitosis?",options:["G1","G2","Anaphase","Cytokinesis"],answer:1 },
  { id:"metaphase-image",code:"2(n)",page:32,format:"image",prompt:"Which feature in the metaphase figure ensures equal chromosome distribution?",options:["Random nuclear-envelope breakdown","Bipolar attachment of sister kinetochores","Crossing over","Cell-plate formation"],answer:1,difficulty:3 },
  { id:"crossing-image",code:"2(t)",page:44,format:"image",prompt:"What is the genetic consequence of the chiasma shown between non-sister chromatids?",options:["Identical parental chromatids only","Recombinant chromatids carrying new allele combinations","Doubling of chromosome number","Loss of all centromeres"],answer:1,difficulty:3 },
  { id:"mitosis-order",code:"2(n)",page:32,format:"sequence",prompt:"Which sequence correctly orders mitosis?",options:["Prophase → metaphase → anaphase → telophase","Metaphase → S phase → prophase → cytokinesis","G1 → meiosis I → G2 → mitosis","Anaphase → prophase → telophase → metaphase"],answer:0 },
  { id:"meiosis-order",code:"2(s)",page:43,format:"sequence",prompt:"Which sequence correctly follows homologous chromosomes through meiosis?",options:["Synapsis/crossing over → bivalents align → homologues separate → sister chromatids separate","DNA replication → sister chromatids separate → homologues pair","Homologues separate → crossing over → DNA replication","Fertilisation → meiosis I → interphase"],answer:0,difficulty:3 },
  { id:"variation-order",code:"2(t)",page:44,format:"sequence",prompt:"Which sequence creates heritable variation through sexual reproduction?",options:["Crossing over and independent assortment → genetically varied gametes → random fertilisation","Mitosis → identical gametes → cloning","DNA repair → identical chromosomes → asexual reproduction","Cytokinesis → S phase → no fertilisation"],answer:0 },
  { id:"dna-data",code:"2(n)",page:24,format:"data",prompt:"A cell has 6 pg DNA in G1. Which row is expected after S phase but before mitosis?",data:{headers:["Stage","DNA / pg","Chromosome number"],rows:[["G1","6","46"],["After S","?","?"]]},options:["12 pg and 46 chromosomes","12 pg and 92 chromosomes","6 pg and 23 chromosomes","3 pg and 46 chromosomes"],answer:0,difficulty:3 },
  { id:"checkpoint-data",code:"2(o)",page:38,format:"data",prompt:"A drug prevents kinetochore attachment. Which result best fits spindle-checkpoint action?",data:{headers:["Treatment","Metaphase cells","Anaphase cells"],rows:[["Control","18","20"],["Drug","76","2"]]},options:["Cells accumulate at metaphase because anaphase is blocked","DNA replication accelerates","Cells enter meiosis","The G1 checkpoint is bypassed"],answer:0,difficulty:3 },
  { id:"assortment-data",code:"2(t)",page:45,format:"data",prompt:"If two homologous pairs assort independently, how many chromosome combinations can gametes receive before considering crossing over?",data:{headers:["Homologous pairs","Possible combinations"],rows:[["1","2"],["2","?"]]},options:["2","4","6","8"],answer:1,explanation:"Independent assortment gives 2^n combinations; with two pairs, 2^2 = 4." },
  { id:"compare-divisions",code:"2(s)",page:45,format:"structured",prompt:"Compare mitosis with meiosis.",markPoints:["Mitosis has one nuclear division whereas meiosis has two","Mitosis produces two cells whereas meiosis usually produces four","Mitosis preserves chromosome number whereas meiosis halves it","Mitosis produces genetically similar cells whereas meiosis produces variation"] },
  { id:"checkpoint-explain",code:"2(o)",page:38,format:"structured",prompt:"Explain how checkpoints reduce the chance of damaged DNA entering daughter cells.",markPoints:["Checkpoint proteins detect DNA damage or incomplete replication","The cycle is arrested before division","Repair can occur or the cell can undergo programmed death","Failure of control allows mutation accumulation and uncontrolled division"] },
  { id:"crossing-explain",code:"2(t)",page:44,format:"structured",prompt:"Explain how crossing over produces genetic variation.",markPoints:["Homologous chromosomes pair during prophase I","Non-sister chromatids break and rejoin at corresponding loci","Equivalent DNA segments are exchanged","Recombinant chromatids contain new combinations of alleles"] },
  { id:"root-practical",code:"2(n)",page:32,format:"practical",prompt:"Plan how to estimate mitotic index in an onion root tip.",markPoints:["Prepare or use stained root-tip squashes and select the meristem","Count cells in mitosis and total cells in several random fields","Calculate mitotic index as dividing cells divided by total cells","Repeat fields or roots and calculate a mean"] },
  { id:"stage-practical",code:"2(n)",page:32,format:"practical",prompt:"How should a student identify anaphase reliably in a root-tip micrograph?",markPoints:["Look for separated sister chromatids or daughter chromosomes","Confirm two groups are moving toward opposite poles","Distinguish from metaphase chromosomes aligned at the equator"] },
  { id:"variation-structured",code:"2(t)",page:45,format:"structured",prompt:"Explain why siblings produced by sexual reproduction are genetically different.",markPoints:["Crossing over forms recombinant chromatids","Independent assortment distributes maternal and paternal homologues randomly","Gametes therefore carry different allele combinations","Random fertilisation combines any one male and female gamete"] },
]);

export const geneExpressionQuestions = build("gene", [
  { id:"semi-conservative",code:"2(a)",page:8,prompt:"What does semi-conservative DNA replication mean?",options:["Each daughter molecule contains one parental and one newly synthesised strand","One daughter receives both old strands","DNA is copied without base pairing","Only half the genes are copied"],answer:0 },
  { id:"meselson",code:"2(a)",page:8,prompt:"After one generation in 14N medium, DNA from 15N-labelled bacteria forms one intermediate-density band. What does this support?",options:["Conservative replication","Semi-conservative replication","No DNA replication","Translation"],answer:1 },
  { id:"helicase",code:"2(a)",page:13,prompt:"What is the role of DNA helicase at a replication fork?",options:["Joins Okazaki fragments","Breaks hydrogen bonds and separates the two strands","Adds RNA primers","Removes telomeres"],answer:1 },
  { id:"primase",code:"2(a)",page:13,prompt:"Why is primase required?",options:["DNA polymerase can only extend from an existing 3′ hydroxyl end","It seals phosphodiester bonds","It proofreads proteins","It separates homologues"],answer:0 },
  { id:"polymerase",code:"2(a)",page:13,prompt:"In which direction does DNA polymerase synthesise a new strand?",options:["3′ to 5′","5′ to 3′","Both simultaneously on one strand","From telomere to centromere only"],answer:1 },
  { id:"lagging",code:"2(a)",page:13,prompt:"Why is the lagging strand made as Okazaki fragments?",options:["Polymerase synthesises only 5′ to 3′ while templates are antiparallel","Helicase works only once","Ligase removes bases","The lagging strand has no template"],answer:0 },
  { id:"ligase",code:"2(a)",page:13,prompt:"What does DNA ligase do during replication?",options:["Breaks hydrogen bonds","Joins adjacent DNA fragments by forming phosphodiester bonds","Adds amino acids","Transcribes primers"],answer:1 },
  { id:"telomere",code:"2(a)",page:24,prompt:"Why do linear chromosomes face an end-replication problem?",options:["The final RNA primer on the lagging strand cannot be replaced because no upstream 3′ end is available","Helicase cannot enter the nucleus","Centromeres are lost every cycle","Leading strands contain no primers"],answer:0,difficulty:3 },
  { id:"transcription",code:"2(b)",page:34,prompt:"Which enzyme synthesises RNA from a DNA template?",options:["DNA ligase","RNA polymerase","Aminoacyl-tRNA synthetase","Peptidyl transferase"],answer:1 },
  { id:"template",code:"2(b)",page:34,prompt:"A DNA template is read 3′ to 5′. In which direction is RNA synthesised?",options:["3′ to 5′","5′ to 3′","From both ends","Without polarity"],answer:1 },
  { id:"splicing",code:"2(b)",page:38,prompt:"What happens during RNA splicing in eukaryotes?",options:["Introns are removed and exons joined","Exons are removed and introns translated","DNA is replicated","A poly-A tail is removed"],answer:0 },
  { id:"cap-tail",code:"2(b)",page:38,prompt:"Which modification helps stabilise eukaryotic mRNA and supports export or translation?",options:["5′ cap and poly-A tail","Removal of every exon","DNA methylation only","Peptide cleavage"],answer:0 },
  { id:"translation",code:"2(b)",page:43,prompt:"What ensures that the correct amino acid is added for an mRNA codon?",options:["Complementary pairing between codon and tRNA anticodon plus correct tRNA charging","DNA helicase","Random peptide bonding","Spindle attachment"],answer:0 },
  { id:"ribosome",code:"2(b)",page:43,prompt:"What is the catalytic role of the ribosome during elongation?",options:["Forms peptide bonds and coordinates tRNA movement","Replicates DNA","Removes introns from DNA","Synthesises ATP"],answer:0 },
  { id:"meselson-image",code:"2(a)",page:8,format:"image",prompt:"Which predicted band pattern after one generation distinguishes semi-conservative from conservative replication?",options:["One intermediate band rather than separate heavy and light bands","Only a heavy band","No band","Three equal bands"],answer:0,difficulty:3 },
  { id:"fork-image",code:"2(a)",page:13,format:"image",prompt:"In the fork diagram, which new strand must be synthesised discontinuously away from the fork?",options:["Leading strand","Lagging strand","Parental coding strand only","mRNA"],answer:1 },
  { id:"splicing-image",code:"2(b)",page:38,format:"image",prompt:"The source shows a longer pre-mRNA and shorter mature mRNA. Which sequences were removed?",options:["Exons","Introns","Codons","Promoters"],answer:1 },
  { id:"replication-order",code:"2(a)",page:13,format:"sequence",prompt:"Which sequence correctly describes initiation and elongation at a replication fork?",options:["Helicase unwinds → primase adds primer → polymerase extends → ligase seals fragments","Ligase unwinds → ribosome translates → helicase seals","Polymerase separates strands → primase removes DNA","Transcription → translation → replication"],answer:0 },
  { id:"expression-order",code:"2(b)",page:34,format:"sequence",prompt:"Which sequence correctly follows eukaryotic gene expression?",options:["Transcription → pre-mRNA processing → nuclear export → translation → protein folding","Translation → replication → splicing","DNA replication → meiosis → transcription only","Splicing → transcription → promoter binding"],answer:0 },
  { id:"translation-order",code:"2(b)",page:43,format:"sequence",prompt:"Which sequence occurs during translation initiation?",options:["Small subunit binds mRNA → initiator tRNA pairs with start codon → large subunit joins","Large subunit copies DNA → introns removed","Stop codon binds first → peptide released","tRNA synthesises mRNA"],answer:0 },
  { id:"meselson-data",code:"2(a)",page:8,format:"data",prompt:"Which model fits the density-band observations?",data:{headers:["Generation in 14N","Bands"],rows:[["0","Heavy"],["1","Intermediate"],["2","Intermediate + light"]]},options:["Semi-conservative","Conservative","Dispersive with one band forever","No replication"],answer:0,difficulty:3 },
  { id:"telomere-data",code:"2(a)",page:24,format:"data",prompt:"Telomere length falls in normal cells but is maintained in a cell line with active telomerase. What is the best inference?",data:{headers:["Division","Normal / kb","Telomerase-active / kb"],rows:[["0","10","10"],["40","7","10"]]},options:["Telomerase extends chromosome ends","Telomerase stops S phase","Normal DNA contains no primers","Telomeres encode ribosomes"],answer:0 },
  { id:"expression-data",code:"2(b)",page:38,format:"data",prompt:"A mutation prevents splicing. Which observation is most likely?",data:{headers:["Sample","pre-mRNA","mature mRNA","protein"],rows:[["Control","low","high","high"],["Mutant","high","low","low"]]},options:["Introns remain and functional protein output falls","Translation accelerates","DNA replication stops in all cells","More mature mRNA forms"],answer:0,difficulty:3 },
  { id:"fork-structured",code:"2(a)",page:13,format:"structured",prompt:"Explain why leading and lagging strands are synthesised differently.",markPoints:["The parental DNA strands are antiparallel","DNA polymerase adds nucleotides only in the 5′ to 3′ direction","The leading strand can be extended continuously toward the fork","The lagging strand is formed away from the fork as Okazaki fragments joined by ligase"] },
  { id:"telomere-structured",code:"2(a)",page:24,format:"structured",prompt:"Explain the end-replication problem in a linear chromosome.",markPoints:["The terminal RNA primer on the lagging strand is removed","No upstream 3′ hydroxyl group is available for DNA polymerase","The resulting gap cannot be filled","The chromosome end therefore shortens after replication"] },
  { id:"transcription-structured",code:"2(b)",page:34,format:"structured",prompt:"Describe transcription in a eukaryotic cell.",markPoints:["Transcription factors and RNA polymerase bind the promoter","DNA unwinds and one strand acts as the template","Complementary ribonucleotides pair and are joined 5′ to 3′","RNA polymerase reaches a termination signal and releases pre-mRNA"] },
  { id:"translation-structured",code:"2(b)",page:43,format:"structured",prompt:"Explain how an mRNA sequence determines a polypeptide sequence.",markPoints:["The ribosome reads mRNA codons in order","tRNA anticodons pair complementarily with codons","Each correctly charged tRNA carries its specific amino acid","Peptide bonds join amino acids until a stop codon terminates translation"] },
  { id:"replication-practical",code:"2(a)",page:8,format:"practical",prompt:"Design the key comparison needed to test whether DNA replication is semi-conservative using isotope-labelled nitrogen.",markPoints:["Grow cells first in heavy nitrogen so parental DNA is labelled","Transfer cells to light nitrogen and sample after defined generations","Separate DNA by density-gradient centrifugation","Compare observed band positions with predictions for competing models"] },
  { id:"rna-practical",code:"2(b)",page:38,format:"practical",prompt:"How could transcript and protein measurements distinguish a transcription defect from a translation defect?",markPoints:["Measure the target mRNA in control and mutant cells","Measure the corresponding protein in the same samples","Low mRNA and protein supports a transcription or RNA-processing defect","Normal mRNA but low protein supports a translation defect"] },
  { id:"code-practical",code:"2(b)",page:43,format:"practical",prompt:"A student tests whether a codon change alters a protein. What evidence should be compared?",markPoints:["Determine the original and mutated DNA or mRNA codons","Use the genetic code to predict the amino acids","Compare protein sequence or size between variants","Include an unchanged control sequence"] },
]);

export const mutationQuestions = build("mutation", [
  { id:"substitution",code:"2(l)",page:5,prompt:"What is a base-pair substitution?",options:["Replacement of one nucleotide pair by another","Addition of a chromosome set","Loss of every exon","Exchange between homologues"],answer:0 },
  { id:"silent",code:"2(l)",page:5,prompt:"Why can a substitution be silent?",options:["The genetic code is degenerate, so the new codon may specify the same amino acid","All substitutions occur in introns","Ribosomes repair DNA","The reading frame always changes"],answer:0 },
  { id:"missense",code:"2(l)",page:5,prompt:"Which mutation changes one codon so that a different amino acid is incorporated?",options:["Missense substitution","Silent substitution","Chromosome inversion only","Polyploidy"],answer:0 },
  { id:"nonsense",code:"2(l)",page:5,prompt:"What is the likely consequence of a nonsense substitution?",options:["A premature stop codon and shortened polypeptide","A longer chromosome set","No transcription initiation","Extra centromeres only"],answer:0 },
  { id:"frameshift",code:"2(l)",page:7,prompt:"Why can a one-base deletion have a large effect on a protein?",options:["It shifts the reading frame and changes downstream codons","It doubles chromosome number","It always leaves every codon unchanged","It prevents DNA from containing bases"],answer:0 },
  { id:"aneuploidy",code:"2(l)",page:16,prompt:"What is aneuploidy?",options:["Gain or loss of individual chromosomes","An exact extra whole genome only","A single base change","Exchange of DNA between sister chromatids"],answer:0 },
  { id:"trisomy",code:"2(l)",page:16,prompt:"Which description identifies trisomy 21?",options:["Three copies of chromosome 21","One copy of every chromosome","Three complete haploid sets","A deletion within chromosome 21 only"],answer:0 },
  { id:"translocation",code:"2(l)",page:16,prompt:"What is a chromosome translocation?",options:["A segment moves to a non-homologous chromosome","A base is replaced","The entire genome doubles","Sister chromatids separate normally"],answer:0 },
  { id:"sickle",code:"2(m)",page:9,prompt:"How does the sickle-cell mutation alter beta-globin?",options:["A substitution changes a glutamic-acid codon to a valine codon","A whole chromosome is lost","Every intron is duplicated","The alpha-globin gene is deleted"],answer:0 },
  { id:"sickle-phenotype",code:"2(m)",page:9,prompt:"Why can deoxygenated sickle haemoglobin distort red blood cells?",options:["Mutant haemoglobin molecules polymerise into fibres","Haemoglobin becomes a lipid","Oxygen breaks chromosomes","Red cells begin mitosis"],answer:0 },
  { id:"carcinogen",code:"2(p)",page:26,prompt:"Why can chemical carcinogens increase cancer risk?",options:["They increase DNA damage and the chance of mutations in growth-control genes","They guarantee DNA repair","They stop every cell cycle","They remove oncogenes"],answer:0 },
  { id:"ras",code:"2(q)",page:26,prompt:"How can a gain-of-function ras mutation promote cancer?",options:["Ras signalling remains active and stimulates division without the normal external signal","Ras removes all growth signals","p53 repairs every mutation","The cell enters meiosis"],answer:0 },
  { id:"p53",code:"2(q)",page:26,prompt:"How can loss of p53 function promote cancer?",options:["Damaged cells fail to arrest, repair DNA or undergo apoptosis","DNA damage is always repaired faster","Growth signalling stops permanently","Chromosome number is halved"],answer:0 },
  { id:"metastasis",code:"2(r)",page:37,prompt:"What distinguishes a malignant tumour from a benign tumour?",options:["Malignant cells invade tissues and can spread to form secondary tumours","Benign tumours always metastasise","Only benign tumours divide","Malignant cells contain no DNA"],answer:0 },
  { id:"mutation-image",code:"2(l)",page:7,format:"image",prompt:"The source shows a one-base insertion followed by altered downstream codons. Which mutation type is illustrated?",options:["Frameshift","Silent substitution","Balanced translocation","Polyploidy"],answer:0 },
  { id:"karyotype-image",code:"2(l)",page:16,format:"image",prompt:"The karyotype contains three copies of chromosome 21. Which chromosome aberration is present?",options:["Trisomy 21","Monosomy X","Triploidy","Inversion"],answer:0 },
  { id:"metastasis-image",code:"2(r)",page:37,format:"image",prompt:"Which event in the illustrated cancer sequence produces a secondary tumour?",options:["Cancer cells leave the primary tumour, travel and colonise another tissue","A normal cell enters G0","Every tumour cell differentiates","The primary tumour loses its blood supply"],answer:0,difficulty:3 },
  { id:"mutation-order",code:"2(m)",page:9,format:"sequence",prompt:"Which sequence links the sickle-cell mutation to symptoms?",options:["DNA substitution → altered codon → Val replaces Glu → haemoglobin polymerises → cells sickle","Trisomy → RNA splicing → normal haemoglobin","Protein mutation → DNA change → normal cells","Metastasis → haemoglobin → meiosis"],answer:0,difficulty:3 },
  { id:"cancer-order",code:"2(r)",page:37,format:"sequence",prompt:"Which sequence best represents multi-step cancer development?",options:["Mutation accumulation → uncontrolled clone → angiogenesis → invasion → metastasis","One mutation → instant secondary tumour without division","Meiosis → fertilisation → benign tumour","DNA repair → checkpoint arrest → metastasis"],answer:0 },
  { id:"oncogene-order",code:"2(q)",page:26,format:"sequence",prompt:"Which sequence connects proto-oncogene mutation to excessive division?",options:["Gain-of-function mutation → oncogene → persistent growth signalling → repeated cell-cycle entry","p53 repair → apoptosis → tumour","Gene deletion → no growth signal → cancer","Meiosis → oncogene loss"],answer:0 },
  { id:"frameshift-data",code:"2(l)",page:7,format:"data",prompt:"Which sample most likely contains a frameshift near the start of the coding sequence?",data:{headers:["Sample","Protein length / aa","Functional activity / %"],rows:[["Wild type","420","100"],["A","419","96"],["B","72","0"]]},options:["Sample B, because altered downstream codons can create an early stop","Sample A only because every one-amino-acid change is frameshift","Wild type","Neither sample"],answer:0,difficulty:3 },
  { id:"sickle-data",code:"2(m)",page:9,format:"data",prompt:"Which conclusion is best supported?",data:{headers:["Genotype","Sickled cells at low O₂ / %"],rows:[["AA","1"],["AS","18"],["SS","82"]]},options:["The S allele increases sickling under low oxygen, with the strongest effect in SS","A causes all sickling","Oxygen has no effect","AS and SS are identical"],answer:0 },
  { id:"cancer-data",code:"2(q)",page:26,format:"data",prompt:"Which interpretation best fits the results?",data:{headers:["Cell line","Active Ras","Functional p53","Division rate"],rows:[["Normal","No","Yes","1.0"],["X","Yes","Yes","2.2"],["Y","Yes","No","5.8"]]},options:["Activated Ras and p53 loss cooperate to increase division","p53 loss stops division","Ras has no effect","Only normal cells divide"],answer:0,difficulty:3 },
  { id:"aberrations-structured",code:"2(l)",page:16,format:"structured",prompt:"Distinguish gene mutation from chromosome aberration and give examples.",markPoints:["A gene mutation changes the nucleotide sequence within a gene","Substitution, insertion or deletion are gene-mutation examples","A chromosome aberration changes chromosome number or structure","Aneuploidy, deletion, inversion, duplication or translocation are chromosome examples"] },
  { id:"sickle-structured",code:"2(m)",page:9,format:"structured",prompt:"Explain how a single base substitution can cause sickle-cell anaemia.",markPoints:["The substitution changes a beta-globin codon","Valine replaces glutamic acid in the beta chain","Deoxygenated mutant haemoglobin polymerises","Red cells become sickle-shaped, obstruct vessels and carry oxygen less effectively"] },
  { id:"genes-structured",code:"2(q)",page:26,format:"structured",prompt:"Compare the roles of ras and p53 mutations in cancer development.",markPoints:["ras is normally a proto-oncogene involved in growth signalling","Gain-of-function ras mutation produces excessive or persistent signalling","p53 is a tumour-suppressor involved in arrest, repair or apoptosis","Loss-of-function p53 mutation allows damaged cells to survive and divide"] },
  { id:"cancer-structured",code:"2(r)",page:37,format:"structured",prompt:"Explain why cancer is described as a multi-step process.",markPoints:["Several mutations accumulate in growth-control genes","A clone gains a selective growth or survival advantage","Angiogenesis supplies an enlarging tumour","Further changes permit invasion and metastasis"] },
  { id:"karyotype-practical",code:"2(l)",page:16,format:"practical",prompt:"How should a student use a karyotype to identify a numerical chromosome aberration?",markPoints:["Arrange homologous chromosomes by size, centromere position and banding pattern","Count each homologous group","Compare the count with the normal diploid complement","Report the affected chromosome and whether it is a gain or loss"] },
  { id:"mutagen-practical",code:"2(p)",page:26,format:"practical",prompt:"Design a safe cell-culture comparison to test whether a chemical increases mutation frequency.",markPoints:["Use untreated cells as a negative control","Expose matched cultures to defined concentrations while controlling other conditions","Measure mutation frequency with the same assay after equal time","Use replicates and compare dose-response means"] },
  { id:"tumour-practical",code:"2(r)",page:37,format:"practical",prompt:"Which observations would distinguish invasion from simple tumour enlargement in tissue sections?",markPoints:["Identify whether tumour cells cross the original tissue boundary or basement membrane","Look for tumour cells within vessels or surrounding tissue","Compare with a benign or normal-tissue control","Sample multiple sections or regions to avoid a single-field conclusion"] },
]);

export const techniqueQuestions = build("technique", [
  { id:"pcr-purpose",code:"2(k)",page:6,prompt:"What is the main purpose of PCR?",options:["Amplify a selected DNA sequence in vitro","Separate proteins by mass","Translate mRNA","Count chromosomes"],answer:0 },
  { id:"pcr-template",code:"2(k)",page:6,prompt:"Which component supplies the sequence to be copied in PCR?",options:["Template DNA","Agarose only","Ethidium bromide only","RNA polymerase"],answer:0 },
  { id:"primers",code:"2(k)",page:6,prompt:"Why are two primers required in PCR?",options:["They define opposite ends of the target and provide 3′ ends for synthesis","They digest DNA","They stain the product","They separate fragments"],answer:0 },
  { id:"taq",code:"2(k)",page:6,prompt:"Why is Taq polymerase used in PCR?",options:["It remains functional after repeated high-temperature denaturation","It fluoresces under UV","It cuts DNA at recognition sites","It moves DNA through agarose"],answer:0 },
  { id:"denaturation",code:"2(k)",page:7,prompt:"What occurs during PCR denaturation?",options:["Hydrogen bonds break and DNA strands separate","Primers form phosphodiester bonds with each other","DNA fragments separate by size","A probe binds a membrane"],answer:0 },
  { id:"annealing",code:"2(k)",page:7,prompt:"What determines the specificity of PCR during annealing?",options:["Complementarity of primers to sequences flanking the target","Agarose concentration only","The colour of loading dye","Centrifugation speed"],answer:0 },
  { id:"extension",code:"2(k)",page:7,prompt:"What occurs at about 72°C in a PCR cycle?",options:["Taq polymerase extends primers by adding complementary nucleotides","DNA is transferred to a membrane","Restriction fragments are stained","RNA is translated"],answer:0 },
  { id:"pcr-limit",code:"2(k)",page:7,prompt:"Why can trace contaminating DNA cause a misleading PCR result?",options:["PCR can amplify the contaminant along with or instead of the intended target","Contamination always stops polymerase","DNA cannot be copied twice","Primers remove contaminants"],answer:0 },
  { id:"gel-charge",code:"2(k)",page:14,prompt:"Why does DNA migrate toward the positive electrode in gel electrophoresis?",options:["Its phosphate backbone is negatively charged","Its bases are positively charged","Agarose pushes it chemically","DNA is magnetic"],answer:0 },
  { id:"gel-size",code:"2(k)",page:14,prompt:"Why do shorter DNA fragments usually travel farther through agarose?",options:["They pass more easily through pores in the gel matrix","They have a positive charge","They contain no phosphate","They are copied by Taq during electrophoresis"],answer:0 },
  { id:"ladder",code:"2(k)",page:14,prompt:"What is the purpose of a DNA ladder in gel electrophoresis?",options:["Provide known fragment sizes for estimating sample-fragment lengths","Amplify the sample","Transfer DNA to a membrane","Denature probes"],answer:0 },
  { id:"southern",code:"2(k)",page:18,prompt:"Why are DNA fragments transferred from a gel to a membrane in Southern blotting?",options:["To immobilise them in the same pattern for probe detection","To amplify them by PCR","To translate them","To restore double helices only"],answer:0 },
  { id:"probe",code:"2(k)",page:20,prompt:"What property allows a labelled nucleic-acid probe to identify a target fragment?",options:["Complementary base pairing","Identical fragment length only","Positive electrical charge","Peptide bonding"],answer:0 },
  { id:"wash",code:"2(k)",page:20,prompt:"Why is the membrane washed after probe hybridisation?",options:["To remove unbound or non-specifically bound probe","To digest every target fragment","To amplify the probe","To reverse electrophoresis"],answer:0 },
  { id:"pcr-image",code:"2(k)",page:7,format:"image",prompt:"Which labelled stage in the source diagram should have the lowest temperature?",options:["Denaturation","Primer annealing","Extension","Final gel staining"],answer:1 },
  { id:"gel-image",code:"2(k)",page:14,format:"image",prompt:"A band lies farther from the wells than another band. What is the most likely inference?",options:["It contains shorter DNA fragments","It contains longer DNA fragments","It is positively charged DNA","It was not loaded"],answer:0 },
  { id:"southern-image",code:"2(k)",page:19,format:"image",prompt:"Why must DNA be denatured before transfer and probe hybridisation?",options:["Single strands expose bases for complementary probe binding","Double strands move faster","Denaturation adds labels","It creates proteins"],answer:0 },
  { id:"pcr-order",code:"2(k)",page:7,format:"sequence",prompt:"Which order describes one PCR cycle?",options:["Denaturation → primer annealing → extension","Extension → electrophoresis → translation","Annealing → Southern transfer → denaturation","Digestion → transcription → extension"],answer:0 },
  { id:"gel-order",code:"2(k)",page:14,format:"sequence",prompt:"Which sequence correctly prepares and runs an agarose gel?",options:["Load DNA and ladder into wells → apply electric field → stain/visualise separated bands","Visualise → amplify → load","Transfer to membrane → translate → run gel","Add ribosomes → apply heat → stain"],answer:0 },
  { id:"southern-order",code:"2(k)",page:18,format:"sequence",prompt:"Which sequence correctly describes Southern blotting?",options:["Digest DNA → electrophoresis → denature → transfer → hybridise labelled probe → wash and detect","PCR → translation → microscopy","Transfer intact cells → add amino acids","Hybridise before fragment separation"],answer:0,difficulty:3 },
  { id:"pcr-data",code:"2(k)",page:7,format:"data",prompt:"Which conclusion follows from the PCR results?",data:{headers:["Tube","Target primers","Template","Band"],rows:[["1","Yes","Patient","Present"],["2","Yes","No-DNA control","Absent"],["3","No","Patient","Absent"]]},options:["The patient sample contains sequence complementary to both primers and contamination is not detected","The no-DNA control is contaminated","Primers are unnecessary","PCR copied all DNA equally"],answer:0,difficulty:3 },
  { id:"gel-data",code:"2(k)",page:14,format:"data",prompt:"Estimate the unknown fragment size from its migration position.",data:{headers:["Band","Distance / mm","Size / bp"],rows:[["Ladder A","20","2000"],["Unknown","34","?"],["Ladder B","36","1000"]]},options:["Slightly above 1000 bp","Much larger than 2000 bp","Exactly 0 bp","Size cannot relate to migration"],answer:0 },
  { id:"blot-data",code:"2(k)",page:20,format:"data",prompt:"A probe binds a 4 kb fragment in sample A and a 6 kb fragment in sample B. What can be concluded safely?",data:{headers:["Sample","Probe-positive band"],rows:[["A","4 kb"],["B","6 kb"]]},options:["Both contain complementary target sequence, but in fragments of different length","Only A contains DNA","B contains more total DNA necessarily","The probe amplified both fragments"],answer:0,difficulty:3 },
  { id:"pcr-structured",code:"2(k)",page:7,format:"structured",prompt:"Explain how repeated PCR cycles amplify a target sequence.",markPoints:["Heat separates the template strands","Primers anneal to complementary sequences flanking the target","Taq polymerase extends from the primers","New molecules become templates so target copy number increases approximately exponentially"] },
  { id:"gel-structured",code:"2(k)",page:14,format:"structured",prompt:"Explain how agarose gel electrophoresis separates DNA fragments.",markPoints:["DNA is negatively charged because of phosphate groups","An electric field pulls DNA toward the positive electrode","The agarose matrix acts as a molecular sieve","Shorter fragments move through pores more easily and travel farther"] },
  { id:"southern-structured",code:"2(k)",page:18,format:"structured",prompt:"Explain how Southern blotting detects one target sequence among many fragments.",markPoints:["DNA fragments are separated by gel electrophoresis","Fragments are denatured and transferred to a membrane in the same pattern","A labelled complementary probe hybridises to the target sequence","Washing removes excess probe and the label reveals the target band"] },
  { id:"compare-structured",code:"2(k)",page:20,format:"structured",prompt:"Distinguish PCR from Southern blotting.",markPoints:["PCR amplifies a selected DNA region whereas Southern blotting detects a sequence among separated fragments","PCR uses primers and thermostable polymerase","Southern blotting uses electrophoresis, membrane transfer and a labelled probe","PCR product amount grows through cycles whereas Southern position also gives fragment-size information"] },
  { id:"pcr-practical",code:"2(k)",page:7,format:"practical",prompt:"Design controls for a diagnostic PCR test.",markPoints:["Include a positive control containing the target sequence","Include a no-template negative control to detect contamination","Use the same master mix and cycling conditions for samples and controls","Interpret a patient band only if both controls give their expected results"] },
  { id:"gel-practical",code:"2(k)",page:14,format:"practical",prompt:"How should a student obtain reliable fragment-size estimates from a gel?",markPoints:["Run a DNA ladder with known fragment sizes in the same gel","Load comparable volumes without puncturing wells","Run the gel under the same voltage and time for all lanes","Compare migration with several ladder bands rather than one band only"] },
  { id:"probe-practical",code:"2(k)",page:20,format:"practical",prompt:"How can hybridisation conditions be adjusted to reduce non-specific probe binding?",markPoints:["Use a probe with strong complementarity to the target","Control temperature and salt concentration to increase stringency","Wash the membrane to remove weakly bound probe","Include a known negative sample to reveal non-specific signal"] },
]);
